### ISSUE TITLE
Warning of dangerous GPG key

### ISSUE THREAD

**Issue by pallaswept** [openSUSE/openSUSE-repos#40]
![image](https://github.com/openSUSE/openSUSE-repos/assets/132128962/6ef1a5cc-2c1b-4e71-9689-e67ae8c00db1)

Enough said! :\

**Comment by andrii-suse** [comment]
my guess is that it is some caching issue when files repodata/repomd.xml* have different expiration times. @dirkmueller @bmwiedemann  I think proper solution would be do not cache these files at all in cdn and always redirect requests for them to download.opensuse.org . Is this something which should be done on MirrorCache side (e.g. with headers) or easier on cdn side?

**Comment by andrii-suse** [comment]
the same https://github.com/openSUSE/MirrorCache/issues/402

**Comment by andrii-suse** [comment]
Alternatively, it could work if we somehow can have identical expiration time for them. But to work 100% smoothly it will require some additions on server side to keep old files on the server a bit longer when new version is released.

**Comment by bmwiedemann** [comment]
For Tumbleweed, we have special publish logic in `/home/mirror/bin/publish_factory` to keep old repo files around for longer.
If we could always send an expiry time to be `($now+300)%300` for both repomd.xml and repomd.xml.asc, that should do the trick. For all repos, there are always some mirrors that still have the old files for a while.

We also try to send purge requests to the CDN at the moment we switch repomd.xml* files but that seems to not have been working for TW so far - maybe because of the use of rsync --link-dest in the publish script. I changed the script a bit to trigger it better.

**Comment by pallaswept** [comment]
> I am afraid that it is not in scope of this package to address this issue.

This package caused this issue, so if not this one. which package's scope should it be within?

**Comment by pallaswept** [comment]
@lkocman these package are still attempting to install every time I start YaST sofware or run zypper inr, and there's till this issue, and the conflict with other software like mirrorsorcerer, and the conflict with customised repository configs. You saif it's not in this project's scope, so what are we supposed to do about this? OpenSUSE is trying to break itself every time I update it or install anything. Are we really just going to ignore me for months about this? Maybe you are just very busy and got distracted but it seems pretty rude and certainly causes serious problems for the entire distro.

**Comment by cluster15** [comment]
I accidentally installed openSUSE-repo during the last update under Leap and just now kicked it off, because the update could not be done, due to above error. And frankly, I want to decide what repositories are to be used not a package. I might as well install Windows if I want to hand over that decision to the software provider.

**Comment by pallaswept** [comment]
The issue being reported here is that the automatically installed package causes an error, demands confirmation that we should take a "big risk", and then prevents all future updates, until it is rolled back and locked out (which is a security risk in itself because now we are not using the intended package sources for our distro). 

If you accidentally installed this package, that is a different problem.

And we've already been told that this issue won't be addressed here, anyway.

> I mean, I should report it _somewhere_, right?

I just wish someone at suse would be so kind as to tell me where to f off to, when they kindly tell me to f off. I guess that makes me entitled lol.

**Comment by cluster15** [comment]
Accidentally in the sense, that I forgot to add --no-recommends for zypper dup and this must have added it to the install. If you manually throw out the repos, that the package installs, it stubbornly re-installs the repos, next time you zypper. 
And it is a really scary sight, seeing something adding those repos (at least it tells you).
